name: ci-go-docker-github-actions
on:
  push:
    branches:
    - main
    - develop

  pull_request:
    branches: 
    - main
    - develop
jobs:
  github-checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'
        check-latest: true
        cache-dependency-path: subdir/go.sum
    - run: go test
    - run: go run main.go


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: emanuelmungu/github-ci-test:latest
  